services:
  gan:
    hostname: gan
    image: cresset:${IMAGE_NAME:-full}
#    ipc: host
    shm_size: 2G
    tty: true
    init: true
    stdin_open: true
    volumes:
      - .:${PROJECT_ROOT:-/opt/project}
    build:
      target: ${TARGET_STAGE:-train}
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_MODE: exclude
        LINUX_DISTRO: ${LINUX_DISTRO:-ubuntu}
        DISTRO_VERSION: ${DISTRO_VERSION:-20.04}
        CUDA_VERSION: ${CUDA_VERSION:-11.5.2}
        CUDNN_VERSION: ${CUDNN_VERSION:-8}
        PYTHON_VERSION: ${PYTHON_VERSION:-3.9}
        MKL_MODE: ${MKL_MODE:-include}  # MKL_MODE can be `include` or `exclude`.
        PROJECT_ROOT: ${PROJECT_ROOT:-/opt/project}
        GID: ${GID:-1000}
        UID: ${UID:-1000}
        GRP: ${GRP:-user}
        USR: ${USR:-user}
        TZ: ${TZ:-Asia/Seoul}
        # URL for faster `apt` and `pip` installs. Optimized for Korean users.
        # Use URLs optimized for user location and security requirements.
        DEB_OLD: ${DEB_OLD:-http://archive.ubuntu.com}
        DEB_NEW: ${DEB_NEW:-http://mirror.kakao.com}
    working_dir: ${PROJECT_ROOT:-/opt/project}
    user: ${UID:-1000}:${GID:-1000}
    environment:
      TZ: ${TZ:-Asia/Seoul}
      CUDA_DEVICE_ORDER: PCI_BUS_ID
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]

